load("//lib:lipo.bzl", "lipo_check", "lipo_create")

lipo_check(binary = ":gh-poi")

lipo_create(
    name = "lipo",
    srcs = [
        "@@rules_multitool++multitool+multitool.gh-poi.macos_arm64//tools/gh-poi:macos_arm64_executable",
        "@@rules_multitool++multitool+multitool.gh-poi.macos_x86_64//tools/gh-poi:macos_x86_64_executable",
    ],
    out = "gh-poi",
)
