load("@rules_python//python:py_binary.bzl", "py_binary")
load("@rules_python//python:py_test.bzl", "py_test")

py_binary(
    legacy_create_init = 0,
    name = "release-worthy",
    srcs = [
        "__init__.py",
        "release-worthy.py",
    ],
)

py_test(
    legacy_create_init = 0,
    name = "weights_test",
    srcs = [
        "__init__.py",
        "weights_test.py",
    ],
)
