name: Bazel build

env:
  HOMEBREW_NO_AUTO_UPDATE: 1

on: [push]

jobs:
  build:
    name: Build on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-12, macos-11]
    steps:
      - uses: actions/checkout@v3
      # action runners have bazelisk: - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel build //...
