---
name: Create Release on New Tag

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    name: "Create Release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: mkdir -p ${HOME}/.cache/bazel
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v3
        with:
          path: "${HOME}/.cache/bazel"
          key: bazel

      - run: bazel build //...

      - name: Create release with Changelog Text
        uses: "marvinpinto/action-automatic-releases@latest"
        env:
          RELEASE_TAG: ${{ github.ref }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.ref }}
          title: Release ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          files: |
            bazel-bin/chickenandbazel.pkg
